#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Starts a Flume NG agent
#
# chkconfig: 345 90 10
# description: Flume NG agent
# author Marcelo Valle <mvalle@keedio.com>
#
### BEGIN INIT INFO
# Provides:          flume-agent
# Required-Start:    $remote_fs
# Should-Start:
# Required-Stop:     $remote_fs
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Flume NG agent
### END INIT INFO

. /lib/lsb/init-functions

if [ -f /etc/default/flume-agent ] ; then
  . /etc/default/flume-agent
fi

if [ -f /etc/profile.d/java.sh ]; then
        . /etc/profile.d/java.sh
        [ -z "\$JAVA_HOME" ] && echo "JAVA_HOME is not defined" && exit 1
else
	echo "enviroment not properly set up"
        exit  1
fi

ERROR_PROGRAM_NOT_INSTALLED=5

FLUME_HOME=/usr/lib/flume

FLUME_AGENT_CONF_DIR=/etc/flume/conf.d
FLUME_RUN_DIR=/var/run/flume
FLUME_LOCK_DIR=/var/lock/subsys
EXEC_PATH=$FLUME_HOME/bin/flume-agent

FLUME_USER=flume

# These directories may be tmpfs and may or may not exist
# depending on the OS (ex: /var/lock/subsys does not exist on debian/ubuntu)
for dir in "$FLUME_RUN_DIR" "$FLUME_LOCK_DIR"; do
  [ -d "${dir}" ] || install -d -m 0755 -o $FLUME_USER -g $FLUME_USER ${dir}
done

start() {
  [ -x $exec ] || exit $ERROR_PROGRAM_NOT_INSTALLED
  getAgentNames
  error=0
  for i in $agentNames
  do
    /bin/su -s /bin/bash -c "${EXEC_PATH} $i status"
    rc=$?
    [ $rc -eq 0 ] && continue
    [ $rc -ne 3 ] && /bin/su -s /bin/bash -c "${EXEC_PATH} $i stop"
    /bin/su -s /bin/bash -c "${EXEC_PATH} $i start"
    ((error+=$?))
  done
  [ $error -eq 0 ] && return 0 || return 1
}

stop() {
  getAgentNames
  error=0
  for i in $agentNames
  do
    /bin/su -s /bin/bash -c "${EXEC_PATH} $i status"
    rc=$?
    [ $rc -eq 3 ] && continue
    /bin/su -s /bin/bash -c "${EXEC_PATH} $i stop"
    ((error+=$?))
  done
  [ $error -eq 0 ] && return 0 || return 1
}

checkstatus() {
  getAgentNames
  running=0
  stopped=0
  error=0
  total=0
  for i in $agentNames
  do
    ((total++))
    /bin/su -s /bin/bash -c "${EXEC_PATH} $i status"
    rc=$?
    if [ $rc -eq 0 ]; then
      ((running++))
    elif [ $rc -eq 3 ]; then
      ((stopped++))
    else
      ((error++))
    fi
  done
  [ $total -eq $stopped ] && echo "Stopped" && return 3
  [ $total -eq $running ] && echo "Running" && return 0
  echo "Error: there are $running agents, $stopped stopped and $error in error state" 
  return 1
}

restart() {
  stop
  [ $? -eq 0 ] && start
  return $?
}

getAgentNames()
{
  agentNames=`ls $FLUME_AGENT_CONF_DIR | cut -f 1 -d '.'`
}

condrestart(){
  getAgentNames
  for i in $agentNames
  do
    lockfile="${FLUME_LOCK_DIR}/flume-agent-$i" 
    [ -e $lockfile] && restart || :
  done
}

case "$1" in
  start)
    start
    RETVAL=$?
    ;;
  stop)
    stop
    RETVAL=$?
    ;;
  status)
    checkstatus
    RETVAL=$?
    ;;
  restart)
    restart
    RETVAL=$?
    ;;
  condrestart|try-restart)
    condrestart
    RETVAL=$?
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
    exit 1
esac

exit $RETVAL
