#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Starts a Flume NG agent
#
# chkconfig: 345 90 10
# description: Flume NG agent
#
### BEGIN INIT INFO
# Provides:          flume-agent
# Required-Start:    $remote_fs
# Should-Start:
# Required-Stop:     $remote_fs
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Flume NG agent
### END INIT INFO

. /lib/lsb/init-functions

if [ -f /etc/default/flume-agent ] ; then
  . /etc/default/flume-agent
fi

if [ -f /etc/profile.d/java.sh ]; then
        . /etc/profile.d/java.sh
        [ -z "\$JAVA_HOME" ] && echo "JAVA_HOME is not defined" && exit 1
else
	echo "enviroment not properly set up"
        exit 1
fi

STATUS_RUNNING=0
STATUS_DEAD=1
STATUS_DEAD_AND_LOCK=2
STATUS_NOT_RUNNING=3

ERROR_PROGRAM_NOT_INSTALLED=5

FLUME_LOG_DIR=/var/log/flume
FLUME_AGENT_CONF_DIR=/etc/flume/conf.d
FLUME_CONF_DIR=/etc/flume/conf
FLUME_RUN_DIR=/var/run/flume
FLUME_HOME=/usr/lib/flume
FLUME_USER=flume

FLUME_LOCK_DIR="/var/lock/subsys/"

desc="Flume NG agent daemon"

EXEC_PATH=/usr/bin/flume-ng

# These directories may be tmpfs and may or may not exist
# depending on the OS (ex: /var/lock/subsys does not exist on debian/ubuntu)
for dir in "$FLUME_RUN_DIR" "$FLUME_LOCK_DIR"; do
  [ -d "${dir}" ] || install -d -m 0755 -o $FLUME_USER -g $FLUME_USER ${dir}
done


DEFAULT_FLUME_AGENT_NAME="agent"
FLUME_AGENT_NAME=${FLUME_AGENT_NAME:-${DEFAULT_FLUME_AGENT_NAME}}
FLUME_SHUTDOWN_TIMEOUT=${FLUME_SHUTDOWN_TIMEOUT:-60}

start() {
  [ -x $exec ] || exit $ERROR_PROGRAM_NOT_INSTALLED

  getAgentNames
  for i in $agentNames
  do
    checkstatus $i
    status=$?
    if [ "$status" -ne "$STATUS_RUNNING" ]; then
  	globalRetval=0
        log_success_msg "Starting $desc (flume-agent $i): "
	flume_pid_file="${FLUME_RUN_DIR}/flume-agent-$i.pid"
	lockfile="${FLUME_LOCK_DIR}/flume-agent-$i"

        #flume_conf_file=${flume_conf_file:-${FLUME_AGENT_CONF_DIR}/$i.conf}
        flume_conf_file=${FLUME_AGENT_CONF_DIR}/$i.conf

        /bin/su -s /bin/bash -c "/bin/bash -c 'echo \$\$ >$flume_pid_file && exec ${EXEC_PATH} agent --conf ${FLUME_CONF_DIR} --conf-file $flume_conf_file --name $i >>${FLUME_LOG_DIR}/$i.out 2>&1' &" $FLUME_USER
        retval=$?
  	[ $retval -eq 0 ] && touch $lockfile
	if [ $retval -ne 0 ]; then
		log_warning_msg "Startup flume-agent $i fails! "
		globalRetval=$retval
	fi
   else
        log_warning_msg "Flume-agent $i is already running"
   fi
  done
  
  return $globalRetval
}

stop() {
  getAgentNames
  for i in $agentNames
  do
          flume_pid_file="${FLUME_RUN_DIR}/flume-agent-$i.pid"
	  lockfile="${FLUME_LOCK_DIR}/flume-agent-$i"
	  if [ ! -e $flume_pid_file ]; then
	    log_failure_msg "Flume agent $i is not running"
	  else
  	    log_success_msg "Stopping $desc (flume-agent) $i:"
   	    flume_pid=`cat $flume_pid_file`
 	     if [ -n $flume_pid ]; then
    		kill -TERM ${flume_pid} &>/dev/null
    		for i in `seq 1 ${FLUME_SHUTDOWN_TIMEOUT}` ; do
      		  kill -0 ${flume_pid} &>/dev/null || break
      		  sleep 1
    		done
    		kill -KILL ${flume_pid} &>/dev/null
 		rm -f $lockfile $flume_pid_file
  	     fi
	  fi   
  done
  return 0
}

restart() {
  stop
  start
}

checkstatus()
{
  flume_pid_file="${FLUME_RUN_DIR}/flume-agent-$1.pid"
  pidofproc -p $flume_pid_file java > /dev/null
  status=$?
 return $status
}

getAgentNames()
{
  agentNames=`ls $FLUME_AGENT_CONF_DIR | cut -f 1 -d '.'`
}

condrestart(){
  getAgentNames
  for i in $agentNames
  do
    lockfile="${FLUME_LOCK_DIR}/flume-agent-$i" 
    [ -e $lockfile] && restart || :
  done
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
    exit 1
esac

exit $RETVAL
