#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Starts a Flume NG agent
#
# chkconfig: 345 90 10
# description: Flume NG agent
# author: Marcelo Valle <mvalle@keedio.com>
#
### BEGIN INIT INFO
# Provides:          flume-agent
# Required-Start:    $remote_fs
# Should-Start:
# Required-Stop:     $remote_fs
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Flume NG agent
### END INIT INFO

. /lib/lsb/init-functions

if [ -f /etc/default/flume-agent ] ; then
  . /etc/default/flume-agent
fi

if [ -f /etc/profile.d/java.sh ]; then
        . /etc/profile.d/java.sh
        [ -z "\$JAVA_HOME" ] && echo "JAVA_HOME is not defined" && exit 1
else
	echo "enviroment not properly set up"
        exit 1
fi



STATUS_RUNNING=0
STATUS_DEAD=1
STATUS_DEAD_AND_LOCK=2
STATUS_NOT_RUNNING=3

ERROR_PROGRAM_NOT_INSTALLED=5

FLUME_LOG_DIR=/var/log/flume
FLUME_CONF_DIR=/etc/flume/conf
FLUME_AGENT_CONF_DIR=/etc/flume/conf.d
FLUME_RUN_DIR=/var/run/flume
FLUME_HOME=/usr/lib/flume
FLUME_USER=flume

FLUME_LOCK_DIR="/var/lock/subsys/"

EXEC_PATH=/usr/bin/flume-ng


# These directories may be tmpfs and may or may not exist
# depending on the OS (ex: /var/lock/subsys does not exist on debian/ubuntu)
for dir in "$FLUME_RUN_DIR" "$FLUME_LOCK_DIR"; do
  [ -d "${dir}" ] || install -d -m 0755 -o $FLUME_USER -g $FLUME_USER ${dir}
done

FLUME_SHUTDOWN_TIMEOUT=${FLUME_SHUTDOWN_TIMEOUT:-60}

start() {
  [ -x $exec ] || exit $ERROR_PROGRAM_NOT_INSTALLED

  checkstatus
  status=$?
  if [ "$status" -eq "$STATUS_NOT_RUNNING" ]; then
    printf "Starting flume agent $flume_agent_name...  "
    
    /bin/su -s /bin/bash -c "/bin/bash -c 'echo \$\$ >$flume_pid_file && exec ${EXEC_PATH} agent  \
    --conf $FLUME_CONF_DIR --conf-file $FLUME_AGENT_CONF_DIR/$flume_agent_name.conf --name $flume_agent_name \
    -Dflume.log.file=flume-agent-$flume_agent_name.log >>${FLUME_LOG_DIR}/flume-agent-$flume_agent_name.out 2>&1' &" $FLUME_USER
    

    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $flume_lockfile && log_success_msg ""
    return $RETVAL
  fi

  if [ "$status" -eq "$STATUS_RUNNING" ]; then
    log_warning_msg "Flume agent $flume_agent_name is already running"
  elif [ "$status" -eq "$STATUS_DEAD" ]; then
    log_failure_msg "Flume agent $flume_agent_name is dead and pid file exists"
  elif [ "$status" -eq "$STATUS_DEAD_AND_LOCK" ]; then 
    log_failure_msg "Flume agent $flume_agent_name is dead and lock file exists"
  else
    log_failure_msg "Flume agent $flume_agent_name status is unknown"
  fi

  return 1
}

stop() {

  checkstatus
  status=$? 
  
  if [ "$status" -eq "$STATUS_RUNNING" ]; then
    flume_pid=`cat $flume_pid_file`
    printf "Stopping flume-agent $flume_agent_name with pid $flume_pid..."


    if [ -n $flume_pid ]; then
      kill -TERM ${flume_pid} &>/dev/null
      for i in `seq 1 ${FLUME_SHUTDOWN_TIMEOUT}` ; do
        kill -0 $flume_pid  &>/dev/null || break
        sleep 1
      done
      kill -KILL $flume_pid &>/dev/null
    fi
  
    rm -f $flume_lockfile $flume_pid_file
    log_success_msg ""
    return 0
  fi

  if [ "$status" -eq "$STATUS_NOT_RUNNING" ]; then
    log_failure_msg "Flume agent $flume_agent_name is not running"
  elif [ "$status" -eq "$STATUS_DEAD" ]; then
    log_warning_msg "Flume agent $flume_agent_name is dead and pid file exists. Triying to remove it..."
    rm -f $flume_pid_file
    log_success_msg "Removed"
  elif [ "$status" -eq "$STATUS_DEAD_AND_LOCK" ]; then 
    log_warning_msg "Flume agent $flume_agent_name is dead and lock file exists. Triying to remove it..."
    rm -f $flume_lockfile
    log_success_msg "Removed"
  else
    log_failure_msg "Flume agent $flume_agent_name status is unknown"
  fi

  return 1
}

restart() {
  stop
  start
}

checkstatus(){
  pidofproc -p $flume_pid_file java > /dev/null
  return $?
}

condrestart(){
  [ -e ${LOCKFILE} ] && restart || :
}

checkConfigFile(){
  if [ ! -f $flume_agent_conf_file ]; then
    log_failure_msg "$flume_agent_name configuration file ($flume_agent_conf_file) doesn't exists in configuration directory ($FLUME_CONF_DIR)"
    exit 1
  fi
}

flume_agent_name=$1
flume_agent_conf_file=${FLUME_AGENT_CONF_DIR}/$1.conf
flume_lockfile=${FLUME_LOCK_DIR}/flume-agent-$flume_agent_name
flume_pid_file=${FLUME_RUN_DIR}/flume-agent-$flume_agent_name.pid

checkConfigFile $flume_agent_name

case "$2" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 <flume-agent-name> {start|stop|status|restart|try-restart|condrestart}"
    exit 1
esac

exit $RETVAL
