#!/bin/sh


if test X"$RPM_INSTALL_PREFIX0" = X"" ; then
  RPM_INSTALL_PREFIX0=/usr/lib/couchbase
fi

systemctl enable couchbase-server
if [ "$INSTALL_DONT_START_SERVER" != "1" ]
then
  systemctl start couchbase-server
else
  echo Skipping server start due to INSTALL_DONT_START_SERVER ...
fi

cat <<EOF

You have successfully installed Couchbase Server.
Please browse to http://`hostname`:8091/ to configure your server.
Please refer to http://couchbase.com for additional resources.

Please note that you have to update your firewall configuration to
allow connections to the following ports:
4369, 8091 to 8094, 9100 to 9105, 9998, 9999, 11209 to 11211,
11214, 11215, 18091 to 18093, and from 21100 to 21299.
EOF

cat <<EOF

By using this software you agree to the End User License Agreement.
See $RPM_INSTALL_PREFIX0/LICENSE.txt.

EOF

exit 0
