#!/bin/sh

if test X"$RPM_INSTALL_PREFIX0" = X"" ; then
  RPM_INSTALL_PREFIX0=/usr/lib/couchbase
fi

if test X"$RPM_INSTALL_PREFIX1" = X"" ; then
  RPM_INSTALL_PREFIX1=/usr/lib/systemd/system
fi

getent group couchbase >/dev/null || \
   groupadd -r couchbase || exit 1
getent passwd couchbase >/dev/null || \
   useradd -r -g couchbase -d $RPM_INSTALL_PREFIX0 -s /sbin/nologin \
           -c "Couchbase system user" couchbase || exit 1

# If Couchbase was previously installed here, stop it
if [ -x $RPM_INSTALL_PREFIX1/couchbase-server.service ]
then
  systemctl stop couchbase-server || true
fi
if [ -x $RPM_INSTALL_PREFIX1/couchbase-server.service ]
then
  systemctl stop couchbase-server || true
fi
# Also check for legacy installs
if [ -x /etc/init.d/couchbase-server ]
then
  /etc/init.d/couchbase-server stop || true
fi

if [ -d /usr/lib/couchbase ]
then
  find /usr/lib/couchbase -maxdepth 1 -type l | xargs rm -f || true
fi

if test -f /sys/kernel/mm/transparent_hugepage/enabled ; then
  if ! grep -q "\[never\]" /sys/kernel/mm/transparent_hugepage/enabled ; then
    cat <<EOF
Warning: Transparent hugepages looks to be active and should not be.
Please look at http://bit.ly/1ZAcLjD as for how to PERMANENTLY alter this setting.
EOF
  fi
fi

if test -f /sys/kernel/mm/redhat_transparent_hugepage/enabled ; then
  if ! grep -q "\[never\]" /sys/kernel/mm/redhat_transparent_hugepage/enabled ; then
    cat <<EOF
Warning: Transparent hugepages looks to be active and should not be.
Please look at http://bit.ly/1ZAcLjD as for how to PERMANENTLY alter this setting.
EOF
  fi
fi

SWAPPINESS=`cat /proc/sys/vm/swappiness`
if [ "$SWAPPINESS" -ne "0" ]
then
    cat <<EOF
Warning: Swappiness is not set to 0.
Please look at http://bit.ly/1k2CtNn as for how to PERMANENTLY alter this setting.
EOF
fi

RAM=`grep 'MemTotal' /proc/meminfo | sed 's/MemTotal:\s*//g' | sed 's/\skB//g' | awk '{printf "%.2f", $1/1024/1024}'`
CPU=`grep 'processor' /proc/cpuinfo | sort -u | wc -l`

cat <<EOF
Minimum RAM required  : 4 GB
System RAM configured : $RAM GB

Minimum number of processors required : 4 cores
Number of processors on the system    : $CPU cores

EOF

exit 0
