#!/bin/sh

if test X"$RPM_INSTALL_PREFIX0" = X"" ; then
  RPM_INSTALL_PREFIX0=/usr/lib/couchbase
fi

# $1 will be 0 only if this is a full uninstall (as opposed to an upgrade)
if [ "$1" = "0" ]
then
  systemctl stop couchbase-server || true
fi

rm -f $RPM_INSTALL_PREFIX0/bin/*.bin

exit 0
